apiVersion: v1
kind: Service
metadata:
  name: teradici-gateway-{{.Release.Name}}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: teradici-gateway-{{.Release.Name}}.{{.Release.Namespace}}.coreweave.cloud
    metallb.universe.tf/address-pool: public-{{ .Values.gateway.region | lower }}
    metallb.universe.tf/allow-shared-ip: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector: 
    coreweave.cloud/ignore: ignore
  ports:
  - name: attach
    port: 1
    protocol: TCP
    targetPort: 1
