apiVersion: v1
kind: ConfigMap
metadata:
  name: sg-config-{{.Release.Name}}
  labels:
data:
  SecurityGateway.conf: |-
    # IP address for Security Gateway to listen on - must be reachable by clients.
    ExternalRoutableIP = teradici-gateway-{{.Release.Name}}.{{.Release.Namespace}}.coreweave.cloud

    # Numeric log level: 0 (trace), 1 (debug), 2 (info), 3 (warn), 4 (error)
    # All messages at or above the configured level will be written to the log.
    LogLevel = 2

    # The following three settings specify the certificate, private key and
    # certificate chain for the TLS connection between the PCoIP client and the SG.
    SSLLinuxExtCert = CMCertificate.pem
    SSLLinuxExtPriv = CMCertificateKey.pem
    SSLLinuxExtCA = CMCertificateCA.pem

    # The following three settings specify the certificate, private key and
    # certificate chain for the control channel TLS connection between the
    # Connection Manager and the SG. If one or more of these settings are missing,
    # the control channel connection is unencrypted.
    TCPControlLinuxExtCert = CMCertificate.pem
    TCPControlLinuxExtPriv = CMCertificateKey.pem
    TCPControlLinuxExtCA = CMCertificateCA.pem

    # --- The following settings are optional and generally should not be modified.
    LogPath = /opt/Teradici/SecurityGateway/log
    MaxConnections = 5000
    SSLCertPath = /opt/Teradici/certs

    tail /opt/Teradici/SecurityGateway/log/`ls /opt/Teradici/SecurityGateway/log`